---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-role
  namespace: datev-wallet
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "update", "delete", "patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-rolebinding
  namespace: datev-wallet
subjects:
- kind: ServiceAccount
  name: default
  namespace: datev-wallet
roleRef:
  kind: Role
  name: configmap-role
  apiGroup: rbac.authorization.k8s.io