apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: datev-secret-store
  namespace: datev-wallet
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-key
          sessionTokenSecretRef:
            name: awssm-secret
            key: session-token