#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# =============================================================================
# Keycloak SSI Deployment Wrapper
# =============================================================================
# Wraps the submodule CLI and adds infrastructure management (Terraform/Helm)
# =============================================================================

# Determine project root
determine_project_root() {
    local script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    # Prefer running locally from the cloned repository
    if [[ -d "$script_dir/keycloak-oauth-sig" ]]; then
        echo "$script_dir"
        return
    fi
    # If installed, use XDG Base Directory
    local xdg_data_home="${XDG_DATA_HOME:-$HOME/.local/share}"
    local project_root="$xdg_data_home/keycloak-ssi-deployment"
    if [[ -d "$project_root/keycloak-oauth-sig" ]]; then
        echo "$project_root"
        return
    fi
    echo "Keycloak SSI project not found. Run from the project root or install with './keycloak-ssi.sh install'." >&2
    exit 1
}

PROJECT_ROOT="$(determine_project_root)"
TEST_DEPLOYMENT_DIR="$PROJECT_ROOT/keycloak-oauth-sig/oid4vci-deployment"
SUBMODULE_CLI="$TEST_DEPLOYMENT_DIR/keycloak-ssi.sh"
SSI_KEYCLOAK_DIR="$PROJECT_ROOT/deployment/keycloak"
SSI_CONFIG="$SSI_KEYCLOAK_DIR/config.override.yaml"
SSI_COMPOSE_OVERRIDE="$SSI_KEYCLOAK_DIR/docker-compose.override.yaml"

# Colors
if [ -t 1 ]; then
  CLI_GREEN="$(printf '\033[0;32m')"
  CLI_YELLOW="$(printf '\033[1;33m')"
  CLI_BLUE="$(printf '\033[1;34m')"
  CLI_RED="$(printf '\033[0;31m')"
  CLI_NC="$(printf '\033[0m')"
else
  CLI_GREEN=""; CLI_YELLOW=""; CLI_BLUE=""; CLI_RED=""; CLI_NC="";
fi

log() { echo -e "${CLI_BLUE}[WRAPPER]${CLI_NC} $1"; }
success() { echo -e "${CLI_GREEN}[SUCCESS]${CLI_NC} $1"; }
warn() { echo -e "${CLI_YELLOW}[WARN]${CLI_NC} $1"; }
error() { echo -e "${CLI_RED}[ERROR]${CLI_NC} $1"; exit 1; }

# =============================================================================
# Helper Functions
# =============================================================================

sync_providers() {
    local providers_dir="$PROJECT_ROOT/providers"
    local -a provider_jars=()
    local -a oid4vp_plugins=()
    local provider

    mapfile -d '' -t provider_jars < <(
        find "$providers_dir" -maxdepth 1 -type f -name '*.jar' -print0
    )
    mapfile -d '' -t oid4vp_plugins < <(
        find "$providers_dir" -maxdepth 1 -type f -name 'keycloak-oid4vp-plugin-*.jar' -print0
    )

    if [[ "${#provider_jars[@]}" -eq 0 ]]; then
        error "No Keycloak provider JARs found in $providers_dir."
    fi

    if [[ "${#oid4vp_plugins[@]}" -ne 1 ]]; then
        error "Expected exactly one keycloak-oid4vp-plugin-*.jar in $providers_dir; found ${#oid4vp_plugins[@]}."
    fi

    log "Using SSI-managed providers:"
    for provider in "${provider_jars[@]}"; do
        log "  - $(basename "$provider")"
    done
}

sync_config() {
    local local_override="$PROJECT_ROOT/config-override.yaml"
    local dest="$TEST_DEPLOYMENT_DIR/config.override.yaml"
    local generated_marker="# Generated by keycloak-ssi-deployment; edit the repository-root config-override.yaml instead."
    local generated_config

    if [[ ! -f "$SSI_CONFIG" ]]; then
        error "SSI Keycloak configuration not found: $SSI_CONFIG"
    fi

    if ! command -v yq >/dev/null 2>&1; then
        error "yq is required to prepare the Keycloak configuration."
    fi

    if [[ -f "$dest" ]] && ! grep -Fqx "$generated_marker" "$dest"; then
        error "An unmanaged $dest already exists. Move its environment-specific values to $local_override before running the wrapper."
    fi

    generated_config="$(mktemp "$dest.tmp.XXXXXX")"
    printf '%s\n' "$generated_marker" > "$generated_config"

    if [[ -f "$local_override" ]]; then
        log "Merging SSI defaults with local configuration from $local_override..."
        if ! yq eval-all '. as $item ireduce ({}; . * $item)' \
            "$SSI_CONFIG" "$local_override" >> "$generated_config"; then
            rm -f "$generated_config"
            error "Could not merge the Keycloak configuration."
        fi
    else
        log "Applying SSI-owned Keycloak configuration..."
        if ! yq eval '.' "$SSI_CONFIG" >> "$generated_config"; then
            rm -f "$generated_config"
            error "Could not prepare the Keycloak configuration."
        fi
    fi

    mv "$generated_config" "$dest"
}

sync_all() {
    sync_providers
    sync_config
}

check_submodule() {
    if [[ ! -f "$SUBMODULE_CLI" ]]; then
        error "Submodule CLI not found at $SUBMODULE_CLI.\nDid you run 'git submodule update --init --recursive'?"
    fi
}

# =============================================================================
# Submodule Extended Commands
# =============================================================================

cmd_scopes() {
    check_submodule
    sync_config
    log "Configuring client scopes independently..."
    (cd "$TEST_DEPLOYMENT_DIR" && bash -c "
        S_GREEN=\"\$(printf '\033[0;32m')\"
        S_YELLOW=\"\$(printf '\033[1;33m')\"
        S_BLUE=\"\$(printf '\033[1;34m')\"
        S_RED=\"\$(printf '\033[0;31m')\"
        S_NC=\"\$(printf '\033[0m')\"

        source src/utils/helper.sh
        setup_environment
        ensure_keycloak_install_dir_resolved
        if ! curl -k -s \"\$KEYCLOAK_ADMIN_ADDR/realms/master\" >/dev/null 2>&1; then
            echo -e \"\${S_RED}[ERROR]\${S_NC} Keycloak is not running. Start it first using './keycloak-ssi.sh setup'.\"
            exit 1
        fi
        
        KCADM=\"\$KEYCLOAK_INSTALL_DIR/bin/kcadm.sh\"
        if [[ ! -x \"\$KCADM\" ]]; then
            echo -e \"\${S_RED}[ERROR]\${S_NC} kcadm.sh not found at: \$KCADM\"
            exit 1
        fi

        \"\$KCADM\" config truststore --trustpass \"\$SSL_TRUST_STORE_PASS\" \"\$SSL_TRUST_STORE\" >/dev/null 2>&1
        \"\$KCADM\" config credentials --server \"\$KEYCLOAK_ADMIN_ADDR\" --realm master \
            --user \"\$KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME\" --password \"\$KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD\" >/dev/null 2>&1

        echo -e \"\${S_BLUE}[INFO]\${S_NC} Creating and assigning client scopes in realm '\$KEYCLOAK_REALM'...\"
        
        TARGET_CLIENTS_STR=\"\${ADD_CLIENT_SCOPES_TARGET_CLIENTS:-openid4vc-rest-api oid4vc-demo-public}\"
        TARGET_CLIENTS_STR=\"\${TARGET_CLIENTS_STR//,/ }\"
        read -ra TARGET_CLIENTS <<< \"\$TARGET_CLIENTS_STR\"
        CLIENT_UUIDS=()
        for cid in \"\${TARGET_CLIENTS[@]}\"; do
            [[ -z \"\$cid\" ]] && continue
            uuid=\$(\"\$KCADM\" get clients -r \"\$KEYCLOAK_REALM\" --query clientId=\"\$cid\" --fields id --format csv --noquotes)
            if [[ -n \"\$uuid\" ]]; then
                CLIENT_UUIDS+=(\"\$uuid\")
            else
                echo -e \"\${S_YELLOW}[WARN]\${S_NC} Client '\$cid' not found in realm '\$KEYCLOAK_REALM'; skipping.\"
            fi
        done

        # Fetch existing scopes once for idempotency checks
        EXISTING_SCOPES=\$(\"\$KCADM\" get client-scopes -r \"\$KEYCLOAK_REALM\" --fields id,name)

        SCOPE_FILE=\"$PROJECT_ROOT/client-scopes.json\"
        if [[ -f \"\$SCOPE_FILE\" ]]; then
            # Inject Issuer DID and process each scope
            CLIENT_SCOPES_CONFIG=\$(jq --arg ISSUER_DID \"\$KEYCLOAK_ISSUER_DID\" 'map(.attributes[\"vc.issuer_did\"] = \$ISSUER_DID)' \"\$SCOPE_FILE\")
            
            echo \"\$CLIENT_SCOPES_CONFIG\" | jq -c '.[]' | while read -r scope; do
                SCOPE_NAME=\$(echo \"\$scope\" | jq -r .name)

                # Check if scope already exists
                SCOPE_UUID=\$(echo \"\$EXISTING_SCOPES\" | jq -r --arg name \"\$SCOPE_NAME\" '.[] | select(.name == \$name) | .id')

                if [[ -n \"\$SCOPE_UUID\" ]]; then
                    echo -e \"\${S_YELLOW}[SKIP]\${S_NC} Client scope '\$SCOPE_NAME' already exists (id: \$SCOPE_UUID).\"
                else
                    # Create scope
                    if echo \"\$scope\" | \"\$KCADM\" create client-scopes -r \"\$KEYCLOAK_REALM\" -f - >/dev/null 2>&1; then
                        echo -e \"\${S_GREEN}[CREATED]\${S_NC} Client scope '\$SCOPE_NAME' created successfully.\"
                        # Refetch ID after creation
                        SCOPE_UUID=\$(\"\$KCADM\" get client-scopes -r \"\$KEYCLOAK_REALM\" --fields id,name | jq -r --arg name \"\$SCOPE_NAME\" '.[] | select(.name == \$name) | .id')
                    else
                        echo -e \"\${S_RED}[ERROR]\${S_NC} Failed to create client scope '\$SCOPE_NAME'.\"
                        continue
                    fi
                fi

                # Assign to target clients only if not already assigned
                if [[ -n \"\$SCOPE_UUID\" ]]; then
                    for cuuid in \"\${CLIENT_UUIDS[@]}\"; do
                        # Check assignment status
                        ASSIGNED=\$(\"\$KCADM\" get \"clients/\$cuuid/optional-client-scopes\" -r \"\$KEYCLOAK_REALM\" --fields id | jq -r --arg sid \"\$SCOPE_UUID\" '.[] | select(.id == \$sid) | .id')
                        
                        if [[ -n \"\$ASSIGNED\" ]]; then
                            echo -e \"\${S_YELLOW}[SKIP]\${S_NC} Scope '\$SCOPE_NAME' already assigned to client \$cuuid.\"
                        else
                            \"\$KCADM\" update \"clients/\$cuuid/optional-client-scopes/\$SCOPE_UUID\" -r \"\$KEYCLOAK_REALM\" >/dev/null 2>&1
                            echo -e \"\${S_GREEN}[ASSIGNED]\${S_NC} Scope '\$SCOPE_NAME' assigned to client \$cuuid.\"
                        fi
                    done
                fi
            done
        else
            echo -e \"\${S_RED}[ERROR]\${S_NC} Scope configuration file not found at \$SCOPE_FILE\"
            exit 1
        fi
    ")
}


cmd_terraform() {
    local tf_dir="$PROJECT_ROOT/infrastructure/terraform"
    log "Delegating to Terraform in $tf_dir..."
    
    if [[ ! -d "$tf_dir" ]]; then
        error "Terraform directory not found at $tf_dir"
    fi

    # Load configuration to pass as environment variables to Terraform
    (
        cd "$TEST_DEPLOYMENT_DIR"
        source src/utils/helper.sh
        setup_environment
        
        # Map Keycloak config to TF_VAR equivalents
        export TF_VAR_keycloak_url="$KEYCLOAK_ADMIN_ADDR"
        export TF_VAR_admin_password="$KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD"
        
        cd "$tf_dir"
        terraform "$@"
    )
}

cmd_helm() {
    local helm_dir="$PROJECT_ROOT/infrastructure/keycloak-chart"
    log "Delegating to Helm (context: $helm_dir)..."
    
    if [[ ! -d "$helm_dir" ]]; then
        error "Helm chart directory not found at $helm_dir"
    fi

    # We'll just run helm in the chart dir for convenience, though helm usually runs from anywhere with paths.
    (cd "$helm_dir" && helm "$@")
}

cmd_compose() {
    check_submodule
    sync_all
    log "Generating a temporary Docker Compose environment from the YAML configuration..."

    (
        cd "$TEST_DEPLOYMENT_DIR"
        WORK_DIR="$TEST_DEPLOYMENT_DIR"
        export WORK_DIR
        source src/utils/helper.sh

        local -a config_files=("$WORK_DIR/config.yaml")
        [[ -f "$WORK_DIR/config.override.yaml" ]] && \
            config_files+=("$WORK_DIR/config.override.yaml")

        local compose_env
        compose_env="$(mktemp)"
        trap 'rm -f "$compose_env"' EXIT

        # Keep YAML as the single source of truth. The temporary env file is
        # only an adapter for Docker Compose, matching the upstream flow.
        export_yaml_as_env "${config_files[@]}" > "$compose_env"
        printf 'KEYCLOAK_FEATURES=%s\n' "$KEYCLOAK_FEATURES" >> "$compose_env"

        local compose_command
        local -a compose_args=()
        compose_command="$(detect_docker_compose)"
        IFS=' ' read -r -a compose_args <<< "$compose_command"
        log "Running Docker Compose without implicit volume deletion..."
        "${compose_args[@]}" \
            --env-file "$compose_env" \
            -f "$TEST_DEPLOYMENT_DIR/docker-compose.yml" \
            -f "$SSI_COMPOSE_OVERRIDE" \
            "$@"
    )
}

cmd_keycloak_stop() (
    WORK_DIR="$TEST_DEPLOYMENT_DIR"
    export WORK_DIR

    source "$WORK_DIR/src/utils/helper.sh"
    init_script

    local keycloak_only=false
    if [[ "${1:-}" == "--keycloak-only" ]]; then
        keycloak_only=true
    fi

    local keycloak_pid
    local stopped=false
    while IFS= read -r keycloak_pid || [[ -n "$keycloak_pid" ]]; do
        [[ -z "$keycloak_pid" ]] && continue
        stopped=true
        log "Stopping Keycloak process $keycloak_pid..."
        kill "$keycloak_pid" 2>/dev/null || true

        local attempt
        for attempt in {1..30}; do
            if ! kill -0 "$keycloak_pid" 2>/dev/null; then
                break
            fi
            sleep 1
        done

        if kill -0 "$keycloak_pid" 2>/dev/null; then
            warn "Keycloak did not stop gracefully; terminating process $keycloak_pid."
            kill -9 "$keycloak_pid" 2>/dev/null || true
        fi
    done < <(get_keycloak_pid || true)

    rm -f "$WORK_DIR/target/keycloak.pid"
    if [[ "$stopped" == "false" ]]; then
        log "No running Keycloak process found."
    fi

    if [[ "$keycloak_only" == "false" ]]; then
        local compose_command
        local -a compose_args=()
        compose_command="$(detect_docker_compose)"
        IFS=' ' read -r -a compose_args <<< "$compose_command"
        log "Stopping the database container while preserving its volume..."
        "${compose_args[@]}" -f "$WORK_DIR/docker-compose.yml" stop db || \
            warn "The database container could not be stopped."
    fi
)

cmd_keycloak_setup() (
    WORK_DIR="$TEST_DEPLOYMENT_DIR"
    export WORK_DIR

    source "$WORK_DIR/src/utils/helper.sh"
    init_script

    local detach_mode=false
    if [[ "${1:-}" == "-d" || "${1:-}" == "--detach" ]]; then
        detach_mode=true
    fi

    # Stop only Keycloak. Preserve PostgreSQL so existing realms can be migrated.
    cmd_keycloak_stop --keycloak-only

    log "Preparing Keycloak $KEYCLOAK_VERSION from the upstream distribution..."
    "$WORK_DIR/src/deployment/setup-kc-oid4vci.sh"

    local compose_command
    local -a compose_args=()
    compose_command="$(detect_docker_compose)"
    IFS=' ' read -r -a compose_args <<< "$compose_command"

    if [[ -z "${DATABASE_OPTS:-}" ]]; then
        log "Starting the existing database container..."
        "${compose_args[@]}" -f "$WORK_DIR/docker-compose.yml" up -d db || \
            error "Could not start the database container."
        DATABASE_OPTS="--db postgres --db-url-port $DATABASE_EXPOSED_PORT --db-url-database $DATABASE_NAME --db-username $DATABASE_USERNAME --db-password $DATABASE_PASSWORD"
    fi

    if [[ -z "${KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME:-}" || -z "${KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD:-}" ]]; then
        error "Bootstrap admin credentials are missing. Configure keycloak.bootstrap in config-override.yaml."
    fi

    log "Installing SSI-managed Keycloak providers..."
    mkdir -p "$KEYCLOAK_INSTALL_DIR/providers"
    local provider
    local provider_count=0
    for provider in "$PROJECT_ROOT"/providers/*.jar; do
        [[ -f "$provider" ]] || continue
        cp "$provider" "$KEYCLOAK_INSTALL_DIR/providers/"
        provider_count=$((provider_count + 1))
    done
    if [[ "$provider_count" -eq 0 ]]; then
        error "No provider JARs found in $PROJECT_ROOT/providers."
    fi

    local -a database_args=()
    local -a start_args=()
    local -a migration_args=()
    IFS=' ' read -r -a database_args <<< "$DATABASE_OPTS"
    IFS=' ' read -r -a start_args <<< "$START_COMMAND"
    if [[ -n "${DATABASE_MIGRATION_STRATEGY:-}" ]]; then
        migration_args+=("--spi-connections-jpa-quarkus-migration-strategy=$DATABASE_MIGRATION_STRATEGY")
    fi

    cd "$KEYCLOAK_INSTALL_DIR"

    log "Ensuring the bootstrap admin exists and migrating the database when required..."
    local bootstrap_status=0
    local bootstrap_output
    bootstrap_output="$(bin/kc.sh bootstrap-admin user \
        --username "$KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME" \
        --password:env KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD \
        "${database_args[@]}" "${migration_args[@]}" 2>&1)" || bootstrap_status=$?

    if [[ "$bootstrap_status" -ne 0 ]]; then
        if grep -Eqi "user with username.*exists|duplicate key value" <<< "$bootstrap_output"; then
            log "Bootstrap admin already exists; continuing."
        else
            printf '%s\n' "$bootstrap_output" >&2
            error "Failed to bootstrap the Keycloak administrator."
        fi
    fi

    export KC_BOOTSTRAP_ADMIN_USERNAME="$KEYCLOAK_BOOTSTRAP_ADMIN_USERNAME"
    export KC_BOOTSTRAP_ADMIN_PASSWORD="$KEYCLOAK_BOOTSTRAP_ADMIN_PASSWORD"

    local log_dir="$WORK_DIR/target"
    mkdir -p "$log_dir"

    log "Starting Keycloak with features: $KEYCLOAK_FEATURES"
    if [[ "$detach_mode" == "true" ]]; then
        local log_file="$log_dir/keycloak.log"
        local keycloak_pid
        nohup bin/kc.sh "${start_args[@]}" "${database_args[@]}" \
            "${migration_args[@]}" "--features=$KEYCLOAK_FEATURES" \
            >"$log_file" 2>&1 &
        keycloak_pid=$!
        printf '%s\n' "$keycloak_pid" > "$log_dir/keycloak.pid"
        disown "$keycloak_pid" 2>/dev/null || true
        log "Keycloak started as process $keycloak_pid; logs: $log_file"
    else
        printf '%s\n' "$$" > "$log_dir/keycloak.pid"
        exec bin/kc.sh "${start_args[@]}" "${database_args[@]}" \
            "${migration_args[@]}" "--features=$KEYCLOAK_FEATURES"
    fi
)

cmd_install() {
    log "Installing keycloak-ssi CLI to system PATH..."

    # Determine install directory
    local install_dir="/usr/local/bin"
    if [[ ! -w "$install_dir" ]]; then
        install_dir="$HOME/.local/bin"
        mkdir -p "$install_dir"
    fi

    local install_path="$install_dir/keycloak-ssi"

    # Install project files to XDG Base Directory using symbolic link
    local xdg_data_home="${XDG_DATA_HOME:-$HOME/.local/share}"
    local project_install_dir="$xdg_data_home/keycloak-ssi-deployment"
    
    log "Installing project files to $project_install_dir..."
    mkdir -p "$xdg_data_home"
    if [[ -e "$project_install_dir" ]]; then
        rm -rf "$project_install_dir"
    fi
    ln -s "$PROJECT_ROOT" "$project_install_dir" || error "Failed to create symbolic link"

    # Install CLI script
    rm -f "$install_path"
    cp "$PROJECT_ROOT/keycloak-ssi.sh" "$install_path"
    chmod +x "$install_path"

    # Check if PATH includes install directory
    if [[ ":$PATH:" != *":$install_dir:"* ]]; then
        warn "Please add $install_dir to your PATH:"
        echo "  export PATH=\"\$PATH:$install_dir\""
    fi

    success "CLI installed to $install_path"
}

cmd_uninstall() {
    log "Uninstalling keycloak-ssi CLI..."
    local locations=("/usr/local/bin/keycloak-ssi" "$HOME/.local/bin/keycloak-ssi")
    for location in "${locations[@]}"; do
        if [[ -f "$location" ]]; then
            rm -f "$location"
            success "Removed $location"
        fi
    done
    local xdg_data_home="${XDG_DATA_HOME:-$HOME/.local/share}"
    local project_install_dir="$xdg_data_home/keycloak-ssi-deployment"
    if [[ -e "$project_install_dir" ]]; then
        rm -f "$project_install_dir"
        success "Removed project files from $project_install_dir"
    fi
}

# =============================================================================
# Main
# =============================================================================

main() {
    local cmd="${1:-help}"
    shift || true

    if ! command -v figlet >/dev/null 2>&1; then
        warn "figlet not found, using fallback (no banner rendering)"

        figlet() {
            local last_arg=""
            for arg in "$@"; do
                [[ "$arg" != -* ]] && last_arg="$arg"
            done
            [[ -n "$last_arg" ]] && echo "$last_arg"
        }
        export -f figlet
    fi

    case "$cmd" in
        setup)
            check_submodule
            sync_all
            
            # Handle --clean flag
            local setup_args=()
            local clean_start=false
            for arg in "$@"; do
                if [[ "$arg" == "--clean" ]]; then
                    clean_start=true
                else
                    setup_args+=("$arg")
                fi
            done

            if [[ "$clean_start" == "true" ]]; then
                log "Clean start requested. Wiping database and existing volumes..."
                cmd_compose down -v
            fi

            log "Starting Keycloak with the SSI-owned deployment wrapper..."
            cmd_keycloak_setup "${setup_args[@]}"
            ;;
        
        config)
            check_submodule
            sync_config
            log "Delegating 'config' to submodule CLI..."
            (cd "$TEST_DEPLOYMENT_DIR" && "$SUBMODULE_CLI" config "$@")
            ;;

        test)
            check_submodule
            sync_config
            log "Delegating 'test' to submodule CLI..."
            (cd "$TEST_DEPLOYMENT_DIR" && "$SUBMODULE_CLI" test "$@")
            ;;

        import)
            check_submodule
            sync_config
            log "Delegating 'import' to submodule CLI..."
            (cd "$TEST_DEPLOYMENT_DIR" && "$SUBMODULE_CLI" import "$@")
            ;;

        stop)
            check_submodule
            sync_config
            log "Stopping Keycloak while preserving its database..."
            cmd_keycloak_stop "$@"
            ;;
        
        compose)
            cmd_compose "$@"
            ;;

        addClientScopes)
            cmd_scopes
            ;;
            
        terraform)
            cmd_terraform "$@"
            ;;
            
        helm)
            cmd_helm "$@"
            ;;

        install)
            cmd_install
            ;;

        uninstall)
            cmd_uninstall
            ;;
            
        help|--help|-h)
            echo "Keycloak SSI Wrapper CLI"
            echo "Usage: ./keycloak-ssi.sh <command> [options]"
            echo ""
            echo "WRAPPER COMMANDS:"
            echo "  setup       Start Keycloak with SSI configuration and providers"
            echo "  addClientScopes     Configure client scopes only (direct API)"
            echo "  terraform   Run terraform commands (auto-manages credentials)"
            echo "  helm        Run helm commands in infrastructure/keycloak-chart"
            echo "  install     Install CLI to system PATH"
            echo "  uninstall   Remove CLI from system PATH"
            echo "  help        Show this help message"
            echo ""
            echo "SUBMODULE/DELEGATED COMMANDS:"
            echo "  config      Run full configuration scripts (submodule)"
            echo "  test        Run OID4VC tests (submodule)"
            echo "  import      Import ready realm configuration"
            echo "  stop        Stop Keycloak and preserve its database volume"
            echo "  compose     Run docker compose commands (e.g., 'up -d', 'down -v')"
            echo ""
            ;;
            
        *)
             echo -e "${CLI_RED}[ERROR]${CLI_NC} Unknown command: $cmd" >&2
             echo "Run './keycloak-ssi.sh help' for usage information."
             exit 1
            ;;
    esac
}

main "$@"
