services:
  app:
    environment:
      KC_SPI_CONNECTIONS_JPA_QUARKUS_MIGRATION_STRATEGY: "${DATABASE_MIGRATION_STRATEGY}"
      KC_SPI_REALM_RESTAPI_EXTENSION_OID4VP_AUTH_MANAGED_REALMS: "${OID4VP_AUTH_MANAGED_REALMS}"
      KC_SPI_REALM_RESTAPI_EXTENSION_OID4VP_AUTH_VERBOSE_ERRORS: "${OID4VP_AUTH_VERBOSE_ERRORS}"
    volumes:
      - ../../providers:/opt/keycloak/providers:ro
