---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: keycloak
        image: ghcr.io/adorsys/keycloak-ssi-deployment:latest
        env:
        - name: KC_DB_HOST
          value: postgres-service
        - name: KC_DB_NAME
          value: keycloakdb
        - name: KC_DB_EXPOSED_PORT
          value: "5432"
        - name: KC_DB_USERNAME
          value: keycloakadmin
        - name: KC_DB_PASSWORD
          value: db-password
        - name: KC_DB_OPTS
          value: "-db postgres --db-url jdbc:postgresql://postgres-service:5432/keycloak --db-username keycloak--db-password keycloak"
        
         # Admin user configurations  
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: admin
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: admin
        - name: KEYCLOAK_HTTPS_PORT
          value: "8443"
        ports:
        - containerPort: 8443
        args:
          - '--spi-db-schema-manager-updates=update'
        volumeMounts:
        - mountPath: /opt/keycloak/data
          name: keycloak-data
      volumes:
      - name: keycloak-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8443
      targetPort: 8443
