---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.0.5
        env:
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL_HOST
          value: postgres-service
        - name: KC_DB_URL_DATABASE
          value: keycloak
        - name: KC_DB_URL_PORT
          value: "5432"
        - name: KC_DB_USERNAME
          value: keycloak
        - name: KC_DB_PASSWORD
          value: keycloak
        
         # Admin user configurations  
        - name: KC_HOSTNAME
          value: keycloak
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: admin
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: admin
        - name: KEYCLOAK_HTTPS_PORT
          value: "8443"
        - name: KC_SERVER_CERT
          value: /path/to/certificate.crt
        - name: KC_SERVER_KEY
          value: /path/to/private.key
        ports:
        - containerPort: 8443
        args:
          - start-dev --features=oid4vc-vci
          - '--spi-db-schema-manager-updates=update'
          - '--hostname-strict=false'
          - '--https-port=$(KEYCLOAK_HTTPS_PORT)'
          - '--https-certificate-file=$(KC_SERVER_CERT)'
          - '--https-certificate-key-file=$(KC_SERVER_KEY)'
        volumeMounts:
        - mountPath: /opt/keycloak/data
          name: keycloak-data
      volumes:
      - name: keycloak-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: LoadBalancer
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8443
      targetPort: 8443
