apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.metadata.name }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.spec.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.spec.secretStoreRef.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.spec.target.name }}
    creationPolicy: {{ .Values.externalSecret.spec.target.creationPolicy }}
  data:
  - secretKey: KC_DB_PASSWORD
    remoteRef:
      key: {{ .Values.awsSecretName }}
      property: KC_DB_PASSWORD