apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "keycloak-chart.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.externalDnsHostname }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    {{- toYaml .Values.keycloak.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.externalDnsHostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.fullnameOverride }}-service
            port:
              number: {{ .Values.keycloak.service.port }}
  tls:
  - hosts:
    {{- range .Values.keycloak.ingress.tls.hosts }}
    - {{ . | quote }}
    {{- end }}
    secretName: {{ .Values.keycloak.ingress.secretName }}