apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.job.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.job.rbac.roleName }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.job.rbac.roleAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
{{- with .Values.job.rbac.rules }}
{{- toYaml . | nindent 2 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.job.rbac.roleBindingName }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.job.rbac.roleBindingAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.job.rbac.roleName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.job.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
