---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak-chart.fullname" . }}-service
  labels:
    app: {{ include "keycloak-chart.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
  - name: {{ .Values.keycloak.service.ports.name }}
    port: {{ .Values.keycloak.service.port }}
    targetPort: {{ .Values.keycloak.service.targetPort }}
  selector:
    app: {{ include "keycloak-chart.name" . }}
