---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak-chart.fullname" . }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.externalDnsHostname }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.certificateArn }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
  labels:
    app: {{ include "keycloak-chart.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.keycloak.service.type }}
  ports:
  - name: https
    port: {{ .Values.keycloak.service.port }}
    targetPort: {{ .Values.keycloak.service.targetPort }}
  selector:
    app: {{ include "keycloak-chart.name" . }}
    
---
{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name }}
  labels:
    app: {{ include "keycloak-chart.name" . }}-postgres
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
  selector:
    app: {{ include "keycloak-chart.name" . }}-postgres
{{- end}}
