fullnameOverride: keycloak
awsSecretName: datev-wallet-secrets
namespace: datev-wallet
externalDnsHostname: keycloak.eudi-adorsys.com

keycloak:
  image:
    repository: ghcr.io/adorsys/keycloak-ssi-deployment
    tag: 1.0.0
    pullPolicy: Always
  secrets: keycloak-secret
  replicas: 1
  service:
    ports:
      name: https
    type: ClusterIP
    port: 8443
    targetPort: 8443
  ingress:
    ingressClassName: nginx
    path: /
    pathType: Prefix
    tls:
      hosts:
        - "*.eudi-adorsys.com"
        - "eudi-adorsys.com"
    secretName: eudi-adorsys-tls
    annotations:
      backendProtocol: "HTTPS"
      sslPassthrough: "true"
      cert-manager.io/cluster-issuer: letsencrypt-prod
  imagePullSecret: ghcr-pull-secret
  envConfigMapName: keycloak-env-config
  volumes:
    - name: env-volume
      configMap:
        name: keycloak-env-config
        optional: true
        items:
          - key: ".env"
            path: ".env"
  volumeMounts:
    - name: env-volume
      mountPath: /opt/keycloak/env

# Postgresql Configuration
postgresql:
  enabled: true
  auth:
    database: keycloakdb
    username: datevadmin
    existingSecret: keycloak-secret
    secretKeys:
      adminPasswordKey: KC_DB_PASSWORD
      userPasswordKey: KC_DB_PASSWORD
  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: high-performance
  service:
    ports:
      postgresql: 5432

# External secrets
externalSecret:
  metadata:
    name: keycloak-external-secret
  spec:
    refreshInterval: 1h
    secretStoreRef:
      name: datev-secret-store
    target:
      name: keycloak-secret
      creationPolicy: Owner

# Job to create config map
metadata:
  name: download-env-file
  namespace: argocd
  annotations:
    hook: PreSync
    hookDeletePolicy: HookSucceeded

volumeMounts:
  name: tmp-volume
  mountPath: /tmp

awsCli:
  image: amazon/aws-cli
  s3Bucket: keycloakenv
  envFilePath: "/tmp/.env"

kubectl:
  image: bitnami/kubectl
  sleepDuration: 5

placeholder:
  image: busybox

job:
  restartPolicy: OnFailure
  serviceAccountName: argocd-server
